/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conversational entry point (text or voice). Gemini-based orchestrator routes to specialist agents.
         * @description Returns `reply` plus `recommendations[]`. The FasalSetu frontend renders one inline card per
         *     recommendation and must not recompute any figure. LLM output never supplies money values.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description Reply plus any recommendations it produced. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatResponse"];
                    };
                };
                422: components["responses"]["Blocked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a farm (country pack selects rules, languages, schema mapping). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FarmCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Farm"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farmId}/plots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farmId: components["parameters"]["farmId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a plot (GPS point enables satellite + SHC lookup). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    farmId: components["parameters"]["farmId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlotCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plot"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a soil sensor reading. `source` must say real or simulated. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SensorReading"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a field photo (feeds photo_health in the tracker). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image: string;
                    };
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/condition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Latest Crop Condition score and components. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CropCondition"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/condition/history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Daily score series. */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CropCondition"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Current recommendation (may be do-nothing) and recent history. */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendation"][];
                    };
                };
            };
        };
        put?: never;
        /** Run the full pipeline now (tracker, agents, revenue, guardrail, log, deliver). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Winning recommendation. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query the event log (scoped to caller's farms). */
        get: {
            parameters: {
                query?: {
                    farm_id?: string;
                    plot_id?: string;
                    event_type?: "recommendation" | "delivery" | "response" | "outcome";
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"][];
                    };
                };
            };
        };
        put?: never;
        /** Append a response or outcome event linked to a recommendation. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventAppend"];
                };
            };
            responses: {
                /** @description Appended */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with its linked children. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    eventId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published JSON Schema for the event (for other countries to validate against). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON Schema document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/irrigation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Irrigation forecast from sensor trend + weather. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IrrigationForecast"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/harvest-window": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Recommended harvest window with money impact per day of delay. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HarvestWindow"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/regenerative": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Ranked regenerative practices (cover crop, intercrop, residue, tillage, amendments). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/satellite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Latest Sentinel-2 NDVI/NDWI for the plot. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SatelliteObservation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grading": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RGB-based produce grading (not hyperspectral). Returns grade plus price effect. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image: string;
                        crop: string;
                        plot_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GradeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leaf-photo disease diagnosis (EfficientNet-B0). Treatment text passes the guardrail. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        image: string;
                        plot_id?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiseaseResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/soil/fertilizer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fertilizer recommendation from SHC values (RF v2; rule-based fallback offline). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SoilInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recommendation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prices from the country pack's source vs support price, with sell/hold view. */
        get: {
            parameters: {
                query: {
                    crop: string;
                    market?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MarketView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Semantic search over the country's schemes. */
        get: {
            parameters: {
                query: {
                    q: string;
                    language?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Scheme"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/season-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plotId: components["parameters"]["plotId"];
            };
            cookie?: never;
        };
        /** Season review ("Crop Wrapped") built from the event log. */
        get: {
            parameters: {
                query?: {
                    season?: string;
                };
                header?: never;
                path: {
                    plotId: components["parameters"]["plotId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SeasonReview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound WhatsApp message/status. Replies like "1 = done" become response events. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inbound SMS reply or delivery receipt. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed packs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/country-packs/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public pack metadata (crops, languages, ruleset version, provenance). Secrets excluded. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PackSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardrail/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent guardrail audit entries. Only available when FS_EXPOSE_AUDIT=true (automatically set when FS_SEED_DEMO=true). Never returns raw query text or personal data.
         * @description Returns the most recent guardrail check records from the server-side JSONL audit log.
         *     Enabled only when FS_EXPOSE_AUDIT=true. Returns 403 otherwise.
         *     Each entry reflects one pre- or post-execution guardrail run.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of most recent entries to return. */
                    last_n?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: components["schemas"]["AuditEntry"][];
                        };
                    };
                };
                /** @description Audit endpoint is disabled (FS_EXPOSE_AUDIT is false). */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness plus which models and data sources are real vs demo. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @example GUARDRAIL_BLOCK */
            code: string;
            message: string;
            rules_triggered?: string[];
        };
        /** @description One guardrail check record. Never contains raw query text or personal data. Enabled only when FS_EXPOSE_AUDIT=true. */
        AuditEntry: {
            /**
             * Format: uuid
             * @description The recommendation event_id this check relates to, if applicable.
             */
            event_id: string | null;
            /** Format: date-time */
            occurred_at: string;
            /**
             * @description The pack ruleset active at the time of the check.
             * @example in@2026.09
             */
            ruleset: string;
            /**
             * @description Result of the pre-execution check.
             * @enum {string}
             */
            pre: "pass" | "block";
            /**
             * @description Result of the post-execution check.
             * @enum {string}
             */
            post: "pass" | "modified" | "block";
            /** @description Names of rules that matched (substance names, not query text). */
            rules_triggered?: string[];
        };
        /** @enum {string} */
        SourceTag: "real" | "simulated" | "satellite" | "api" | "farmer_reported";
        ChatRequest: {
            farm_id: string;
            plot_id?: string;
            /** @example hi */
            language?: string;
            input: {
                text?: string;
                audio_base64?: string;
                image_base64?: string;
            };
        };
        ChatResponse: {
            reply: string;
            language: string;
            audio_url?: string;
            recommendations?: components["schemas"]["Recommendation"][];
            agents_used?: string[];
        };
        FarmCreate: {
            country: string;
            region?: string;
            preferred_language: string;
            /** @enum {string} */
            channel: "chat" | "sms" | "whatsapp" | "voice";
            /** @description Stored in-country only; never enters the event log. */
            contact?: string;
        };
        Farm: components["schemas"]["FarmCreate"] & {
            farm_id?: string;
        };
        PlotCreate: {
            crop: string;
            variety?: string;
            /** Format: date */
            sowing_date?: string;
            lat: number;
            lon: number;
            area_ha: number;
            irrigation_type?: string;
        };
        Plot: components["schemas"]["PlotCreate"] & {
            plot_id?: string;
            farm_id?: string;
        };
        SensorReading: {
            /** Format: date-time */
            observed_at: string;
            source: components["schemas"]["SourceTag"];
            soil_moisture_pct: number;
            soil_temp_c?: number;
            device_id?: string;
        };
        InputComponent: {
            value: number | null;
            unit?: string;
            source: components["schemas"]["SourceTag"];
            /** Format: date-time */
            observed_at?: string;
        };
        CropCondition: {
            plot_id: string;
            /** Format: date */
            date: string;
            score: number;
            /** @enum {string} */
            band?: "good" | "watch" | "stressed" | "critical";
            components: {
                soil_moisture?: components["schemas"]["InputComponent"];
                weather_stress?: components["schemas"]["InputComponent"];
                photo_health?: components["schemas"]["InputComponent"];
                ndvi?: components["schemas"]["InputComponent"];
            };
        };
        RevenueImpact: {
            formula_version?: string;
            currency: string;
            expected_yield_kg?: number;
            grade_adjusted_price_per_kg?: number;
            action_cost?: number;
            risk_discount?: number;
            net_impact: number;
            loss_if_ignored?: number | null;
            confidence?: number;
            assumptions: {
                price_source: string;
                /** Format: date-time */
                price_observed_at?: string;
                yield_baseline: string;
                risk_discount_rate: number;
                /** @constant */
                estimated?: true;
            };
        };
        GuardrailResult: {
            ruleset?: string;
            /** @enum {string} */
            pre?: "pass" | "block";
            /** @enum {string} */
            post?: "pass" | "modified" | "block";
            rules_triggered?: string[];
        };
        Recommendation: {
            /**
             * Format: uuid
             * @description The logged recommendation event.
             */
            event_id: string;
            agent: string;
            category: string;
            is_do_nothing: boolean;
            /** @description Rendered in the farmer's language. */
            text: string;
            /** Format: date-time */
            act_by?: string | null;
            revenue: components["schemas"]["RevenueImpact"];
            guardrail: components["schemas"]["GuardrailResult"];
            reference?: string;
        };
        EventAppend: {
            /** Format: uuid */
            parent_event_id: string;
            /** @enum {string} */
            event_type: "response" | "outcome";
            /** @description Validated against the published event schema. */
            payload: Record<string, never>;
        };
        /** @description See /events/schema for the authoritative definition. */
        EventEnvelope: {
            [key: string]: unknown;
        };
        IrrigationForecast: {
            /** Format: date-time */
            next_irrigation_at?: string | null;
            moisture_trend?: {
                /** Format: date-time */
                t?: string;
                pct?: number;
                forecast?: boolean;
            }[];
            recommendation?: components["schemas"]["Recommendation"];
        };
        HarvestWindow: {
            /** Format: date */
            start?: string;
            /** Format: date */
            end?: string;
            loss_per_day_delay?: number;
            recommendation?: components["schemas"]["Recommendation"];
        };
        SatelliteObservation: {
            /** Format: date */
            observed_at?: string;
            ndvi?: number;
            ndwi?: number;
            cloud_cover_pct?: number;
            /** @example Sentinel-2 L2A */
            provider?: string;
        };
        GradeResult: {
            grade?: string;
            confidence?: number;
            /** @constant */
            method?: "rgb-opencv";
            /** @example RGB only; not hyperspectral. */
            limitations?: string;
            price_effect_per_kg?: number;
            recommendation?: components["schemas"]["Recommendation"];
        };
        DiseaseResult: {
            label?: string;
            confidence?: number;
            top_k?: {
                label?: string;
                p?: number;
            }[];
            recommendation?: components["schemas"]["Recommendation"];
        };
        SoilInput: {
            crop: string;
            ph: number;
            organic_carbon: number;
            ec: number;
            n?: number;
            p?: number;
            k?: number;
            plot_id?: string;
        };
        MarketView: {
            crop?: string;
            price_per_quintal?: number;
            support_price?: number | null;
            source?: string;
            /** Format: date-time */
            observed_at?: string;
            /** @enum {string} */
            advice?: "sell" | "hold" | "unknown";
        };
        Scheme: {
            id?: string;
            name?: string;
            summary?: string;
            eligibility?: string;
            url?: string;
            score?: number;
            /** @description Optional. e.g. SUBSIDY, DIRECT_TRANSFER, INSURANCE, CREDIT, MSP */
            benefit_type?: string;
            /** @description Optional. Human-readable benefit amount or range, e.g. '₹6,000/year' or 'Up to 50%'. */
            benefit_amount?: string | null;
            /**
             * @description Optional. CENTRAL or STATE.
             * @enum {string}
             */
            level?: "CENTRAL" | "STATE";
            /** @description Optional. State name if level=STATE; null for central schemes. */
            state?: string | null;
        };
        SeasonReview: {
            plot_id?: string;
            season?: string;
            currency?: string;
            actions_recommended?: number;
            actions_taken?: number;
            do_nothing_calls?: number;
            predicted_impact_taken?: number;
            realized_impact?: number | null;
            timeline?: components["schemas"]["Recommendation"][];
            next_season_adjustments?: string[];
        };
        PackSummary: {
            code?: string;
            name?: string;
            languages?: string[];
            crops?: string[];
            currency?: string;
            guardrail_ruleset?: string;
            /** @enum {string} */
            completeness?: "full" | "thin";
            data_provenance?: string;
            /** @description Public read-only substance lists from the pack's compliance section. All entries reflect the seed lists; set verified=false until confirmed against the national regulator. */
            compliance_substances?: {
                banned?: components["schemas"]["ComplianceSubstance"][];
                restricted?: components["schemas"]["ComplianceSubstance"][];
            };
        };
        ComplianceSubstance: {
            /** @example endosulfan */
            substance: string;
            /**
             * @description Regulatory authority or citation that establishes the restriction.
             * @example CIB&RC / Supreme Court order
             */
            source: string;
            /**
             * @description Date the entry was last verified against the authority source.
             * @example VERIFY
             */
            retrieved_on: string;
            /** @description false for all current seed entries — these are illustrative only and must be verified against the national regulator before any real use. */
            verified: boolean;
        };
        Health: {
            status?: string;
            models?: {
                [key: string]: string;
            };
            data?: {
                [key: string]: "real" | "demo" | "simulated";
            };
        };
    };
    responses: {
        /** @description Blocked by the pre-execution guardrail (e.g. banned pesticide). Logged to audit trail. */
        Blocked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        farmId: string;
        plotId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
